name: flutter_application_5
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.7 # For fingerprint recognition
  flutter_blue: ^0.8.0 # For Bluetooth functionality

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
