
name: flutter_fingerprint_lock_app
description: A Flutter app to unlock via fingerprint and Bluetooth.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.3
  flutter_bluetooth_serial: ^0.4.0
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
