name: btlockapp
description: A Flutter Bluetooth + Fingerprint lock app

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial:
    git:
      url: https://github.com/edufolly/flutter_bluetooth_serial.git
  local_auth: ^2.1.7

flutter:
  uses-material-design: true
